name: MealClock
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"

targets:
  MealClock:
    type: application
    platform: iOS
    sources:
      - path: MealClock
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.mealclock
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
    info:
      properties:
        CFBundleDisplayName: MealClock
        UILaunchStoryboardName: LaunchScreen
        UIUserInterfaceStyle: Light
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false