name: MealClock

options:
  deploymentTarget:
    iOS: "17.0"  # set this to <= your phone’s iOS version

targets:
  MealClock:
    type: application
    platform: iOS

    sources:
      - path: MealClock

    resources:
      # Keep LaunchScreen.storyboard at repo root (per your repo layout)
      - path: LaunchScreen.storyboard

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.mealclock
        SWIFT_VERSION: "5.0"

    info:
      path: MealClock/Info.plist
      properties:
        CFBundleDisplayName: MealClock
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
