name: MealClock

options:
  bundleIdPrefix: com.philtheappguy

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  MealClock:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: MealClock
    resources:
      - path: LaunchScreen.storyboard
      - path: MealClock/Assets.xcassets
    info:
      path: MealClock/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.philtheappguy.MealClock
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []
      gatherCoverageData: false

configs:
  Debug: debug
  Release: release
