name: MealClock

options:
  deploymentTarget:
    iOS: "14.0"

targets:
  MealClock:
    type: application
    platform: iOS
    sources:
      - path: MealClock
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.mealclock
        SWIFT_VERSION: "5.0"
    info:
      properties:
        CFBundleDisplayName: MealClock
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
