name: MealClock

options:
  deploymentTarget:
    iOS: "17.0"

targets:
  MealClock:
    type: application
    platform: iOS

    sources:
      - path: MealClock
        excludes:
          - Assets.xcassets

    resources:
      - path: MealClock/Assets.xcassets
      - path: LaunchScreen.storyboard

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.mealclock
        SWIFT_VERSION: "5.0"

        # ✅ makes the app actually use MealClock/Assets.xcassets/AppIcon.appiconset
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

        # optional (only matters if you have AccentColor in Assets.xcassets)
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

    info:
      path: MealClock/Info.plist
      properties:
        CFBundleDisplayName: MealClock
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
